name: Patch

on:
  workflow_dispatch:
jobs:
  Version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.previoustag.outputs.tag }}
      changelog: ${{ steps.changelog.outputs.changelog }}
    steps:
      - name: Checkout 
        uses: actions/checkout@v3  
        with:
          fetch-depth: 0 
      
      - name: Get Previous tag
        id: previoustag
        uses: WyriHaximus/github-action-get-previous-tag@v1.3.0  
        with:
          fallback: 1.0.0
          
      - name: Get changelog
        id: changelog
        run: |
          echo 'changelog<<CHANGELOG_BODY_EOF' >> $GITHUB_OUTPUT
          echo "$(curl https://gist.githubusercontent.com/vinaghost/f7ce5204670e8194eea71a3961405c2f/raw/)" >> $GITHUB_OUTPUT
          echo 'CHANGELOG_BODY_EOF' >> $GITHUB_OUTPUT
  Build:
    runs-on: windows-latest
    needs: Version
    strategy:
      matrix:
        server: [TRAVIAN_OFFICIAL, TTWARS]
    steps:
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
        
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Load cached dependencies
        uses: actions/cache@v3
        with:
            path: ~/.nuget/packages
            key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
            restore-keys: ${{ runner.os }}-nuget-

      - name: Install dependencies
        run: dotnet restore --locked-mode
      
      - name: Publish
        run: dotnet publish WPFUI -c Release --no-restore --self-contained -p:PublishSingleFile=true -p:Server=${{ matrix.server }} -p:AssemblyVersion=${{needs.version.outputs.version}}
        
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: TBS-${{ matrix.server }}
          path: WPFUI\bin\Release\net6.0-windows\win-x64\publish\
          if-no-files-found: error
                  
  Release:
    runs-on: ubuntu-latest
    permissions:
        contents: write
    needs: [Build, Version]
    steps:        
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          path: TBS
      
      - name: Archive release
        run: |
          cd TBS; zip -r "TBS-${{needs.version.outputs.version}}-TravianOfficial.zip" TBS-TRAVIAN_OFFICIAL; cp -R "TBS-${{needs.version.outputs.version}}-TravianOfficial.zip" ../; cd ..
          cd TBS; zip -r "TBS-${{needs.version.outputs.version}}-TTWars.zip" TBS-TTWARS; cp -R "TBS-${{needs.version.outputs.version}}-TTWars.zip" ../; cd ..
      
      - name: Create release
        uses: ncipollo/release-action@v1.13.0
        with:
          name: TBS-${{needs.version.outputs.version}}
          tag: ${{needs.version.outputs.version}}
          commit: main
          artifacts: "TBS-${{needs.version.outputs.version}}-TravianOfficial.zip, TBS-${{needs.version.outputs.version}}-TTWars.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            Please join our Discord server for more information: [https://discord.gg/mBa4f2K](https://discord.gg/mBa4f2K)
            
            **Changelog**: 
              ${{needs.version.outputs.changelog}}
  Discord:
    if: false
    runs-on: ubuntu-latest
    needs: [Release, Version] 
    steps:
      - name: Ping @everyone
        run: |
          curl --header "Content-Type: application/json" --data "{\"content\": \"@everyone\"}" "${{ secrets.DISCORD_BOT }}"
      - name: Send to discord server
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_BOT }}
          title: New patch
          nodetail: true
          description: |
            Version `TBS-${{needs.version.outputs.version}}`
            Click [here](https://github.com/vinaghost/TravianBotSharp/releases/tag/${{needs.version.outputs.version}}) to download!
            
            **Changelog**:              
            ${{needs.version.outputs.changelog}}
  Clear:  
    runs-on: ubuntu-latest
    needs: Release
    strategy:
      matrix:
        server: [TRAVIAN_OFFICIAL, TTWARS]
    steps:
      - name: Delete artifact
        uses: geekyeggo/delete-artifact@v2
        with:
          name: TBS-${{ matrix.server }}
